version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: agora_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Oracle123
      MYSQL_DATABASE: agora_db
    ports:
      - "3307:3306" # Cambiar de 3306 a 3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint/agora.sql:/docker-entrypoint-initdb.d/agora.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build: .
    container_name: agora_django
    command: >
      sh -c "sleep 10 &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=agora_db
      - DB_USER=root
      - DB_PASSWORD=Oracle123
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  mysql_data:
